### ISSUE TITLE
hass errors after upgraded

### ISSUE THREAD

**Issue by nutinshell** [fbradyirl/ciscomobilityexpress#13]
Sorry if report not properly HASS issue here...

After upgraded to 0.1.4, HASS reports errors:

```
2019-03-27 01:15:54 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/homeassistant/components/device_tracker/__init__.py", line 716, in async_device_tracker_scan
    host_name = await scanner.async_get_device_name(mac)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/homeassistant/components/cisco_mobility_express/device_tracker.py", line 64, in get_device_name
    if result.macaddr == device), None)
  File "/usr/local/lib/python3.7/dist-packages/homeassistant/components/cisco_mobility_express/device_tracker.py", line 64, in <genexpr>
    if result.macaddr == device), None)
AttributeError: 'Device' object has no attribute 'clId'
```

PS, I got about 30-50 devices in ME system :)

**Comment by fbradyirl** [comment]
Thanks @nutinshell can you try version `0.1.5`. You clearly have a bigger network than me! ;)

**Comment by nutinshell** [comment]
@fbradyirl fixed no more >10 devices! But oops... all new devices come out with name in MAC format

![image](https://user-images.githubusercontent.com/211299/55083409-7789eb80-50de-11e9-9ded-ebed9053a702.png)

**Comment by fbradyirl** [comment]
@nutinshell yes that will always be the case when the `clId` is empty.

**Comment by fbradyirl** [comment]
The AP doesn't have the name of those devices.
